import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/app/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex">
                    <div className="w-[300px] h-screen bg-gray-900 text-white">
                        <Sidebar />
                    </div>
                    <main className="flex-1 ">{children}</main>
                </div>
            </body>
        </html>
    );
}
